syndromic (observed, 
          dates=data.frame(), 
          min.date=NULL, 
          max.date=NULL, 
          date.format="%d/%m/%Y", 
          weekends=TRUE, 
          baseline=matrix(nrow=0,ncol=0), 
          alarms=array(dim=0), 
          UCL=array(dim=0), 
          LCL=array(dim=0))
           
raw_to_syndromic (id,
                  syndromes.var, 
                  syndromes.name,
                  dates.var, 
                  date.format="%d/%m/%Y", 
                  min.date, 
                  max.date,
                  remove.dow=FALSE,
                  add.to=0,
                  sort=TRUE,
                  data=NULL)

retro_summary(x,
              object.name="my.syndromic",
              file.name="syndromic.retro.summary",
              frequency=365,
              short=FALSE)
             
             
clean_baseline(x,
               syndromes=NULL,
               family="poisson",
               limit=0.95,
               formula="dow+sin+cos+year+AR1+AR2+AR3+AR4+AR5+AR6+AR7",
               plot=TRUE,
               print.model=TRUE)

clean_baseline_perc(x,
                    syndromes=NULL,
                    limit=0.95,
                    run.window=120,
                    plot=TRUE)

holt_winters_synd(x,
                  syndromes=NULL,
                  evaluate.window=1,
                  frequency=7,
                  baseline.window=365,
                  limit.sd=c(2.5,3,3.5),
                  nahead=7,
                  alpha=0.4,
                  beta=0,
                  gamma=0.15,
                  seasonal="additive",
                  correct.baseline=1,
                  alarm.dim=1,
                  UCL=1)

ewma_synd(x,
          syndromes=NULL,
          evaluate.window=1,
          baseline.window=365,
          lambda=0.2,
          limit.sd=c(2.5,3,3.5),
          guard.band=7,
          correct.baseline=FALSE,
          alarm.dim=2,
          UCL=1,
          LCL=FALSE,
          pre.process=FALSE,
          diff.window=7,
          family="poisson",
          formula="dow+sin+cos+year+AR1+AR2+AR3+AR4+AR5+AR6+AR7",
          period=365)

pre_process_glm(x,
                slot="observed",
                syndromes=NULL,
                family="poisson",
                formula="dow+sin+cos+year+AR1+AR2+AR3+AR4+AR5+AR6+AR7",
                period=365,
                print.model=TRUE,
                plot=TRUE)

shew_synd(x,
          syndromes=NULL,
          evaluate.window=1,
          baseline.window=365,
          limit.sd=c(2.5,3,3.5),
          guard.band=7,
          correct.baseline=FALSE,
          alarm.dim=3,
          UCL=1,
          LCL=FALSE,
          pre.process=FALSE,
          diff.window=7,
          family="poisson",
          formula="dow+sin+cos+year+AR1+AR2+AR3+AR4+AR5+AR6+AR7",
          period=365)

cusum_synd(x,
            syndromes=NULL,
            evaluate.window=1,
            baseline.window=365,
            limit.sd=c(2.5,3,3.5),
            guard.band=7,
            correct.baseline=FALSE,
            alarm.dim=4,
            UCL=1,
            LCL=FALSE,
            pre.process=FALSE,
            diff.window=7,
            family="poisson",
            formula="dow+sin+cos+year+AR1+AR2+AR3+AR4+AR5+AR6+AR7",
            period=365)

update_syndromic(x,
                 id,
                 syndromes.var, 
                 add.syndromes=TRUE,
                 dates.var, 
                 date.format="%d/%m/%Y", 
                 remove.dow=FALSE,
                 add.to=0,
                 replace.dates=TRUE,
                 data=NULL)

plot_syndromic(x,
               syndromes=NULL,
               window=365,
               baseline=TRUE,
               UCL=1,
               algorithms=NULL,
               limit=1)

syndromic_alarm(x,
                pdf.report=TRUE,
                email.alarm.to=NULL,
                email.noalarm.to=NULL,
                date=NULL,
                plot.all=FALSE,
                window=365,
                baseline=TRUE,
                UCL=1,
                algorithms=NULL,
                limit=1,
                email.from=NULL,
                smtpServer=NULL,
                subject= paste((Sys.Date()),"ALARM: There are alarms today",sep=","),
                message=NULL,
                height=7.5,
                width=10.5,
                pdf.dir=TRUE,
                file.name=NULL)

Syndromic_page(x,
               week=7,
               window=365,
               baseline=TRUE,
               UCL=1,
               algorithms=NULL,
               limit=1,
               file.name="my.syndromic",
               title=file.name,
               data.page=FALSE,
               data=NULL,
               date.format="%d/%m/%Y",
               dates.var=NULL,
               syndromes.var=NULL,
               color.null="F8F8FF",
               color.low="F8FF2F",
               color.alarm="FF0000",
               scale=9, 
               fill.colors=c("yellow2","orange","tomato"),
               arrow.colors=c("green","orange","tomato","red"))
